#!/usr/bin/env bash
# Commands to install nginx on web server

# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get install nginx

# Allow Nginx traffic through the firewall
sudo ufw 'Nginx HTTP'

# Display a message to confirm the installation
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
