#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02

# Update packages
sudo apt-get update
sudo apt-get install -y nginx

# Create the inxex page
echo "Hello World!" | sudo tee /var/www/html/index

# Perform redirection
my_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/josephorokpo permanent;"

sudo sed -i "s/server_name _;/$my_string/" /etc/nginx/sites-enabled/default

# Create a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Add custom http response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t 

# Restart server
sudo service nginx restart
