#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02

# Update packages
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 414818-web-01:80 check
    server web-02 414818-web-02:80 check
EOF

# Enable HAProxy service
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy
