#!/usr/bin/env bash

# Correct Nginx configuration to listen on port 80
# Navigate to the directory containing Nginx enabled sites configurations
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Remove the default configuration file
rm default;                                                                                                                                               
# Create a symbolic link to the default configuration file in the sites-available directory
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restart the Nginx service
service nginx restart
