#!/usr/bin/env bash
# Configures a container to run Nginx as the nginx user, listen on all active IPs on port 8080.
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
